export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_PLAYLIST_CHANGE = "HANDLE_PLAYLIST_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_ANIME_BEGIN = "CREATE_ANIME_BEGIN";
export const CREATE_ANIME_SUCCESS = "CREATE_ANIME_SUCCESS";
export const CREATE_ANIME_ERROR = "CREATE_ANIME_ERROR";

export const GET_ANIMES_BEGIN = "GET_ANIMES_BEGIN";
export const GET_ANIMES_SUCCESS = "GET_ANIMES_SUCCESS";

export const FETCH_ANIMES_BEGIN = "FETCH_ANIMES_BEGIN";
export const FETCH_ANIMES_SUCCESS = "FETCH_ANIMES_SUCCESS";
export const FETCH_ANIMES_ERROR = "FETCH_ANIMES_ERROR";

export const GET_PLAYLIST_BEGIN = "GET_PLAYLIST_BEGIN";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";

export const UPDATE_PLAYLIST_BEGIN = "UPDATE_PLAYLIST_BEGIN";
export const UPDATE_PLAYLIST_SUCCESS = "UPDATE_PLAYLIST_SUCCESS";
export const UPDATE_PLAYLIST_ERROR = "UPDATE_PLAYLIST_ERROR";

export const CREATE_PLAYLIST_BEGIN = "CREATE_PLAYLIST_BEGIN";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";

export const DELETE_ANIME_BEGIN = "DELETE_ANIME_BEGIN";
export const DELETE_ANIME_SUCCESS = "DELETE_ANIME_SUCCESS";

export const DELETE_PLAYLIST_BEGIN = "DELETE_PLAYLIST_BEGIN";
export const DELETE_PLAYLIST_SUCCESS = "DELETE_PLAYLIST_SUCCESS";
export const DELETE_PLAYLIST_ERROR = "DELETE_PLAYLIST_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const CHANGE_SITE_LANGUAGE = "CHANGE_SITE_LANGUAGE";

export const CHANGE_DEFAULT_PLAYLIST_POLICY = "CHANGE_DEFAULT_PLAYLIST_POLICY";
