export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const DELETE_USER_BEGIN = "DELETE_USER_BEGIN";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const HANDLE_PLAYLIST_CHANGE = "HANDLE_PLAYLIST_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_ANIME_BEGIN = "CREATE_ANIME_BEGIN";
export const CREATE_ANIME_SUCCESS = "CREATE_ANIME_SUCCESS";
export const CREATE_ANIME_ERROR = "CREATE_ANIME_ERROR";

export const GET_ANIMES_BEGIN = "GET_ANIMES_BEGIN";
export const GET_ANIMES_SUCCESS = "GET_ANIMES_SUCCESS";

export const DELETE_ANIME_BEGIN = "DELETE_ANIME_BEGIN";
export const DELETE_ANIME_SUCCESS = "DELETE_ANIME_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const CHANGE_SITE_LANGUAGE = "CHANGE_SITE_LANGUAGE";
